# Generated by Django 5.2.13 on 2026-04-28 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackoutperiod',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='blackoutperiod',
            name='start_date',
        ),
        migrations.AddField(
            model_name='blackoutperiod',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blackoutperiod',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
