# Generated by Django 5.2.13 on 2026-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ผู้ดูแลระบบ (Admin)'), ('lecturer', 'อาจารย์ (Lecturer)'), ('student', 'นักศึกษา (Student)')], default='lecturer', help_text="User's role in the system", max_length=20),
        ),
    ]
