# Generated by Django 5.2.14 on 2026-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ผู้ดูแลระบบ (Admin)'), ('lecturer', 'อาจารย์ (Lecturer)')], default='lecturer', help_text="User's role in the system", max_length=20),
        ),
    ]
