# Generated by Django 5.2.14 on 2026-05-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_role'),
        ('account', '0005_user_notification_email_alter_user_role'),
    ]

    operations = [
    ]
