# Generated by Django 5.2.6 on 2026-04-18 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_pattern', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_groups', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_groups', to='rooms.room')),
            ],
            options={
                'db_table': 'recurring_groups',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'รอการอนุมัติ'), ('Approved', 'อนุมัติแล้ว'), ('Rejected', 'ปฏิเสธ'), ('Cancelled', 'ยกเลิก')], default='Pending', max_length=10)),
                ('purpose_type', models.CharField(choices=[('teaching', 'สอน'), ('training', 'อบรม')], max_length=10)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_approved', to=settings.AUTH_USER_MODEL)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_booker', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room')),
                ('recurring_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.recurringgroup')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='TeachingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('Bachelor', 'ปริญญาตรีภาคปกติ'), ('Master', 'ปริญญาโท'), ('TEP-TEPE', 'TEP-TEPE'), ('TU-PINE', 'TU-PINE')], max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_info', to='bookings.booking')),
            ],
            options={
                'db_table': 'teaching_info',
            },
        ),
        migrations.CreateModel(
            name='TrainingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_info', to='bookings.booking')),
            ],
            options={
                'db_table': 'training_info',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'start_datetime', 'end_datetime', 'status'], name='idx_conflict_detection'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_datetime'], name='idx_report_filter'),
        ),
    ]
