# Generated by Django 6.0.4 on 2026-04-08 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('purpose_type', models.CharField(choices=[('teaching', 'สอน/ชดเชย/เสริม'), ('training', 'อบรม/ติว')], max_length=20)),
                ('subject_code', models.CharField(blank=True, max_length=20)),
                ('subject_name', models.CharField(blank=True, max_length=200)),
                ('program_type', models.CharField(blank=True, choices=[('undergraduate', 'ปริญญาตรีภาคปกติ'), ('graduate', 'ปริญญาโท'), ('tep_tepe', 'TEP-TEPE'), ('tu_pine', 'TU-PINE')], max_length=20)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_group_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room')),
            ],
        ),
    ]
