# Generated by Django 5.2.13 on 2026-04-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, help_text='คำขอเพิ่มเติมจากผู้จอง', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='หมายเหตุจากแอดมินตอนอนุมัติ', null=True),
        ),
    ]
